serve:
  admin:
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1
        - http://localhost:8080
        - http://localhost:5173
        - http://localhost
        - https://staging.canvas.unlockedlabs.xyz
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - X-Requested-With
      exposed_headers:
        - Content-Type

  public:
    cors:
      enabled: true
      allowed_origins:
        - http://localhost
        - https://staging.canvas.unlockedlabs.xyz
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
        - Access-Control-Allowed-Origins
  cookies:
    same_site_mode: None
log:
  leak_sensitive_values: true

urls:
  self:
    issuer: http://127.0.0.1
  consent: http://127.0.0.1/consent
  login: http://127.0.0.1:4433/self-service/login/browser
  logout: http://127.0.0.1:4433/self-service/login/browser

dev: true
secrets:
  system:
    - Vg2CngwLX2MxZvZaKJnuyVp66cPiiV5bCHANGE_ME_IN_PROD
oidc:
  subject_identifiers:
    supported_types:
      - pairwise
    pairwise:
      salt: 2839o82hy2839OO#@#$@OFw@ksj8*^@*^$LSwsifw2692oCHANGE_ME_IN_PROD
