services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USER=unlocked
  #     - DB_PASSWORD=dev
  #     - DB_NAME=unlocked
  #     - MIGRATE_FRESH=${MIGRATE_FRESH}
  #     - PROVIDER_SERVICE_URL=http://provider-service:8081
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ".env"
  #   command: >
  #     sh -c '
  #     while ! nc -z  postgres 5432; do
  #       sleep 3;
  #     done;
  #     ./backend'
  # provider-service:
  #   build:
  #     context: ./backend/provider-middleware
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - server
  #   env_file: ".env"
  #   command: ./provider-service

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: unlocked
      POSTGRES_USER: unlocked
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
