services:
  # requires logging in to our ECR account
  kolibri:
    image: unlockedlabs.org/kolibri:latest
    ports:
      - 8000:8000
    networks:
      - intranet
    depends_on:
      - postgres
