services:
  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - APP_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=unlocked
      - DB_PASSWORD=dev
      - DB_NAME=unlocked
      - LOG_LEVEL=debug
      - APP_URL=http://127.0.0.1
      - PROVIDER_SERVICE_URL=http://provider-service:8081
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://hydra:4444
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KETO_ADMIN_URL=http://keto:4466
      - ORY_TOKEN=eyJvZmZzZXQiOiItMjUwIiwidmo8iV*@
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kratos-migrate:
        condition: service_completed_successfully
    env_file:
      - "./backend/.env"
    command: >
      ./backend
    volumes:
      - logs:/logs/
    networks:
      - intranet

  # Proxy requests to vite devserver
  rev_proxy:
    volumes:
      - ./config/fe-dev.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: [server]

  # Provider middleware
  provider-service:
    build:
      context: ./provider-middleware
      dockerfile: Dockerfile
    env_file: "./backend/.env"
    command: ./provider-service
    networks:
      - intranet
    volumes:
      - logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
