version: v0.8.0-alpha.2

log:
  level: debug

namespaces:
  - id: 0
    name: student

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: postgres://keto:ChangeMe!@postgres:5432/keto?sslmode=prefer&max_cons=20&max_idle_cons=4
